Pause CI until DB issues can be resolved

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -5,71 +5,71 @@ name: Tracker v3 CI
 #    branches: [ main ]
 #  pull_request:
 #    branches: [ main ]
-
-jobs:
-  build:
-    runs-on: [ ubuntu-latest ]
-
-    services:
-      mariadb:
-        image: mariadb:latest
-        ports:
-          - 3306
-        env:
-          MYSQL_USER: sail
-          MYSQL_PASSWORD: password
-          MYSQL_DATABASE: tracker
-          MYSQL_ROOT_PASSWORD: password
-        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
-
-    strategy:
-      matrix:
-        php:
-          - "8.1"
-
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Verify MariaDB connection
-        env:
-          PORT: ${{ job.services.mariadb.ports[3306] }}
-        run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
-            sleep 1
-          done
-
-      - uses: "shivammathur/setup-php@v2"
-        with:
-          php-version: "${{ matrix.php }}"
-
-      - name: Copy .env
-        run: php -r "file_exists('.env') || copy('.env.github', '.env');"
-
-      - name: Setup CI Authentication
-        run: |
-          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_API_USER }} ${{ secrets.NOVA_API_KEY }}
-
-      - name: Install dependencies
-        uses: "ramsey/composer-install@v1"
-        with:
-          dependency-versions: "locked"
-          composer-options: "--prefer-dist --no-cache --ignore-platform-reqs"
-
-      - name: Generate key
-        run: php artisan key:generate
-
-      - name: Directory Permissions
-        run: chmod -R 777 storage bootstrap/cache
-
-      - name: Configure matchers
-        uses: mheap/phpunit-matcher-action@v1
-
-      - name: Run Tests
-        env:
-          DB_PORT: ${{ job.services.mariadb.ports['3306'] }}
-        run: ./vendor/bin/phpunit --colors=always
-
-      - uses: sarisia/actions-status-discord@v1
-        if: always()
-        with:
-          webhook: ${{ secrets.DISCORD_ADMIN_WEBHOOK }}
+#
+#jobs:
+#  build:
+#    runs-on: [ ubuntu-latest ]
+#
+#    services:
+#      mariadb:
+#        image: mariadb:latest
+#        ports:
+#          - 3306
+#        env:
+#          MYSQL_USER: sail
+#          MYSQL_PASSWORD: password
+#          MYSQL_DATABASE: tracker
+#          MYSQL_ROOT_PASSWORD: password
+#        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+#
+#    strategy:
+#      matrix:
+#        php:
+#          - "8.1"
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#
+#      - name: Verify MariaDB connection
+#        env:
+#          PORT: ${{ job.services.mariadb.ports[3306] }}
+#        run: |
+#          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
+#            sleep 1
+#          done
+#
+#      - uses: "shivammathur/setup-php@v2"
+#        with:
+#          php-version: "${{ matrix.php }}"
+#
+#      - name: Copy .env
+#        run: php -r "file_exists('.env') || copy('.env.github', '.env');"
+#
+#      - name: Setup CI Authentication
+#        run: |
+#          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_API_USER }} ${{ secrets.NOVA_API_KEY }}
+#
+#      - name: Install dependencies
+#        uses: "ramsey/composer-install@v1"
+#        with:
+#          dependency-versions: "locked"
+#          composer-options: "--prefer-dist --no-cache --ignore-platform-reqs"
+#
+#      - name: Generate key
+#        run: php artisan key:generate
+#
+#      - name: Directory Permissions
+#        run: chmod -R 777 storage bootstrap/cache
+#
+#      - name: Configure matchers
+#        uses: mheap/phpunit-matcher-action@v1
+#
+#      - name: Run Tests
+#        env:
+#          DB_PORT: ${{ job.services.mariadb.ports['3306'] }}
+#        run: ./vendor/bin/phpunit --colors=always
+#
+#      - uses: sarisia/actions-status-discord@v1
+#        if: always()
+#        with:
+#          webhook: ${{ secrets.DISCORD_ADMIN_WEBHOOK }}
